#ifndef WORD__KEY_H
#define WORD__KEY_H

JChar key[][] = {
{A, A, I, E, BA, KO, U, I, U},
{A, _, RU, NO, NA, I, TU, KI, NO, KA, KI, HA, YO, KU, NA, I},
{A, I, E, N, KI, E, N},
{A, I, O, O, KE, RE, BA, NI, KU, SI, MI, I, TA, RU},
{A, I, KU, TI, NI, TU, BA},
{A, I, GO, SE, I, MO, KU},
{A, I, SA, TU, HA, TO, KI, NO, U, ZI, GA, MI},
{A, I, SA, TU, YO, RI, E, N, SA, TU},
{A, I, SO, ZU, KA, SI, MO, KA, NE, KA, RA, O, KI, RU},
{A, I, SO, MO, KO, SO, MO, TU, KI, HA, TE, RU},
{A, I, TA, I, NO, KO, TO, HA, KO, TI, XYA, SI, RA, NU},
{A, I, TA, KU, TI, GA, FU, SA, GA, RA, NA, I},
{A, I, TA, KU, TI, NI, HA, TO, HA, TA, TA, NU},
{A, I, TA, KU, TI, HE, BO, TA, MO, TI},
{A, I, DU, TI, WO, U, TU},
{A, I, TE, KA, WA, RE, DO, NU, SI, KA, WA, RA, ZU},
{A, I, TE, NO, SA, SU, RU, KO, U, MI, XYO, U},
{A, I, TE, NO, NA, I, KE, N, KA, HA, DE, KI, NU},
{A, I, TE, MI, TE, KA, RA, NO, KE, N, KA, GO, E},
{A, I, HA, O, SI, MI, NA, KU, A, TA, U},
{A, I, HA, KO, DA, SI, NI, SE, YO},
{A, I, HA, ZO, U, O, NO, HA, ZI, ME},
{A, I, BE, TU, RI, KU},
{A, I, BO, RE, U, NU, BO, RE, KA, TA, BO, RE, O, KA, BO, RE},
{A, I, MA, I, MO, KO},
{A, I, MO, DO, RI, HA, KA, MO, NO, A, ZI},
{A, U, HA, WA, KA, RE, NO, HA, ZI, ME},
{A, U, N, NO, KO, KI, XYU, U},
{A, E, TE, SI, XYU, TO, NA, RA, ZU, KI, XYA, KU, TO, NA, RU},
{A, E, BA, GO, RI, N, NO, SO, N, GA, YU, KU},
{A, O, I, KI, TO, I, KI},
{A, O, I, DE, TE, N, NI, HA, ZI, ZU},
{A, O, I, TO, RI},
{A, O, GA, KI, GA, ZI, XYU, KU, SI, TO, MU, RA, U},
{A, O, TA, GA, I},
{A, O, TA, HO, ME, RA, RE, BA, KA, HO, ME, RA, RE},
{A, O, NA, NI, SI, O},
{A, O, NI, SA, I},
{A, O, HA, A, I, YO, RI, I, DE, TE, A, I, YO, RI, A, O, SI},
{A, O, BA, HA, ME, NO, KU, SU, RI},
{A, O, BI, XYO, U, SI, WO, TA, TA, I, TA, MO, NO, NI, HA, KA, NA, WA, NU},
{A, KA, I, HA, SA, KE, NO, TO, GA},
{A, GA, KI, GA, TO, RE, NA, I},
{A, KA, GO, NO, U, TI, HA, NA, NA, KU, NI, NA, NA, KU, SA, TO, NO, MO, NO, NI, NI, RU},
{A, KA, GO, NO, TE, WO, NE, ZI, RU, YO, U},
{A, KA, GO, HA, NA, KI, NA, KI, SO, DA, TU},
{A, KA, GO, HA, DA, RE, KA, NI, SI, TA, YO, U},
{A, KA, DE, SI, N, DA, MO, NO, HA, NA, I},
{A, KA, NO, TA, NI, N},
{A, KA, MO, MI, NO, U, TI},
{A, KA, RU, KE, RI, XYA, TU, KI, YO, DA, TO, O, MO, U},
{A, KI, A, RE, HA, N, SA, KU},
{A, KI, KA, ZE, GA, TA, TU},
{A, KI, KA, ZE, TO, HU, U, HU, GE, N, KA, HA, HI, GA, I, RI, XYA, YA, MU},
{A, KI, DA, RU, HA, O, TO, GA, TA, KA, I},
{A, KI, }
}

#endif
