#ifndef WORD__STD2
#define WORD__STD2

JChar std2[][] = {
    {A  , I  }, {A  , O  }, {A  , KA }, {A  , KI }, {A  , KU }, {A  , GO }, {A  , SA }, {A  , ZA }, {A  , SI }, {A  , ZI }, {A  , SU }, {A  , SE }, {A  , ZE }, {A  , DA }, {A  , TE }, {A  , TO }, {A  , NA }, {A  , NI }, {A  , NE }, {A  , BU }, {A  , MA }, {A  , MI }, {A  , ME }, {A  , YA }, {A  , YU }, {A  , RA }, {A  , RI }, {A  , RE }, {A  , WA }, {A  , N  },
    {I  , E  }, {I  , KA }, {I  , GA }, {I  , KI }, {I  , GI }, {I  , KE }, {I  , GO }, {I  , SI }, {I  , ZI }, {I  , SU }, {I  , SO }, {I  , TA }, {I  , TI }, {I  , TU }, {I  , TO }, {I  , DO }, {I  , NU }, {I  , NE }, {I  , BO }, {I  , MA }, {I  , MO }, {I  , RI }, {I  , RO }, {I  , YA }, {I  , WA }, {I  , N  },
    {U  , E  }, {U  , O  }, {U  , KA }, {U  , KI }, {U  , KE }, {U  , SI }, {U  , ZI }, {U  , SU }, {U  , ZU }, {U  , SO }, {U  , TA }, {U  , TI }, {U  , DE }, {U  , DO }, {U  , NI }, {U  , NE }, {U  , HA }, {U  , BA }, {U  , MA }, {U  , MI }, {U  , MU }, {U  , ME }, {U  , RA }, {U  , RI },
    {E , A },
    {E , I },
    {E , KI},
    {E , SA},
    {E , SU},
    {E , ZU},
    {E , ZO},
    {E , DA},
    {E , TE},
    {E , TO},
    {E , BI},
    {E , MA},
    {E , MI},
    {E , MU},
    {E , RA},
    {E , RI},
    {E , RU},
    {E , N },
    {O , I },
    {O , U },
    {O , KA},
    {O , KI},
    {O , KU},
    {O , KE},
    {O , SI},
    {O , ZI},
    {O , SU},
    {O , TI},
    {O , TU},
    {O , TO},
    {O , NI},
    {O , NE},
    {O , NO},
    {O , BA},
    {O , BI},
    {O , HU},
    {O , MO},
    {O , YA},
    {O , RI},
    {O , N },
}

#endif
